### ISSUE TITLE
Cannot read property 'update' of null

### ISSUE THREAD

**Issue by NameFILIP** [krispo/angular-nvd3#109]
After navigating to another state of a ui-router, when resizing the window I get a lot of repetitions of the next error in the console: `Uncaught TypeError: Cannot read property 'update' of null` at
https://github.com/krispo/angular-nvd3/blob/v1.0.0-beta/src/angular-nvd3.js#L139

Options:
```
$scope.chart = {
      options: {
        chart: {
          type: 'multiBarChart',
          height: 600,
          showControls: false,
          rotateLabels: -65,
          reduceXTicks: false,
          margin: {
            bottom: 200
          },
          yAxis: {
            tickFormat: function (d) {
              return d3.format('d')(d) + ' ms';
            }
          },
          tooltipContent: function (key, x, y, graph) {
            return '<h3>' + key + '</h3><p>' + x + ' : '+  y + '</p>';
          }
        }
      }
    };
```

**Comment by praveenaj** [comment]
I'm getting the same error. Any solutions?

**Comment by praveenaj** [comment]
The fix is to edit Line #143 with this:
```
scope.chart.resizeHandler = nv.utils.windowResize(function() { scope.chart && scope.chart.update(); });
```

**Comment by miguelrincon** [comment]
I an related issue, at the same line, I am getting when switching between states with charts in them.

```
  Uncaught TypeError: Cannot set property 'resizeHandler' of null
```

**Comment by kamilbrk** [comment]
Got the same issue. Looks like window resize handler is not removed correctly on scope $destroy in .clearElement() method. Line #173:

```javascript
if (scope.chart.resizeHandler) scope.chart.resizeHandler.clear();
```

And #341 where it runs:
```javascript
// remove completely when directive is destroyed
element.on('$destroy', function () {
    scope.api.clearElement();
});
```

**Comment by rfink** [comment]
+1, same issues

**Comment by gsemwezi** [comment]
I experienced the same issue on the line below:
https://github.com/krispo/angular-nvd3/blob/master/src/angular-nvd3.js#L139
Fixed it by checking if scope.chart is not null or undefined before executing that line.
Similar issue occurs on the line below:
https://github.com/krispo/angular-nvd3/blob/master/src/angular-nvd3.js#L173
Some index of nv.graphs, is usually null or undefined and hence the error.

**Comment by kytwb** [comment]
:+1:

**Comment by PhilFlash** [comment]
+1, same issues

**Comment by IngoVals** [comment]
I've implemented the changes #123 but I'm still having problems.

In `nv.addGraph` I get that `scope.chart.update()` is undefined

**Comment by chocstarfish** [comment]
Is there any updates on this issue? I am still having the same problem when resizing the container of the chart.

**Comment by kylecordes** [comment]
We've seen the same issue, hoping for a fix to appear. We've worked around it with something like what praveenaj wrote.

**Comment by NameFILIP** [comment]
Investigated the issue today. Turns out, because of the async execution, `clearElement(..)` is called before the handlers were added. In my case, 3 resize handlers were added to the window (try `getEventListeners(window).resize`). 
On destroy the latest one was removed, chart was set to null, but two others were still there. That's why we got the "Can't read the property .. of null". Moved the removing resize handler to the same async function.
Review the PR if you'd like, I'll merge it tomorrow https://github.com/krispo/angular-nvd3/pull/165

**Comment by inolasco** [comment]
I'm having this same issue using rc2. Seems the code has this:

    scope.chart.update && scope.chart.update()

Shouldn't it be this instead?

    scope.chart && scope.chart.update()

If scope.chart is null, then the first check will still fail

**Comment by NameFILIP** [comment]
Yep, looks like the handlers are still not removed properly. Should be investigated more

**Comment by mchicote** [comment]
+1

**Comment by EoinGriffin-AI** [comment]
I worked around this by adding this to line 195:

```
if (scope.chart && scope.chart.resizeHandler) {
    scope.chart.resizeHandler.clear();
}
```

**Comment by christian-steinmeyer** [comment]
+1

**Comment by CautemocSg** [comment]
+1

The workaround posted above by @EoinGriffin-AI works, but for rc.2 it should go on like 190, above scope.chart = null;.

**Comment by lcarva** [comment]
Any updates on this?

**Comment by curtismorte** [comment]
To tack on to @lcarva's answer, we should also check scope.chart during invocation of scope.chart.resizeHandler. Remember, we're playing with objects here so the anonymous function passed as the first parameter will run (when invoked), and the first check for scope.chart will happen on the scope object. However there is still a chance that the scope object can be updated from the time of the anonymous function is executed to the time scope.chart.resizeHandler is invoked.

```
nv.addGraph(function() {
  if (scope.chart) {
    // Remove resize handler. Due to async execution should be placed here, not in the clearElement
    if (scope.chart.resizeHandler) scope.chart.resizeHandler.clear();
    // Update the chart when window resizes
    scope.chart.resizeHandler = nv.utils.windowResize(function() {
	    if (scope.chart) 
        	scope.chart.update && scope.chart.update();
    });
  }
  return scope.chart;
}, options.chart['callback']);
```

**Comment by krispo** [comment]
Thanks all! It fixed in the latest versions [1.0.4+]
